import React,{useState} from "react";import{createRoot}from"react-dom/client";import{Activity,CloudLightning,Satellite,Upload,Wind}from"lucide-react";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
function App(){const[file,setFile]=useState(null),[pattern,setPattern]=useState(null),[fc,setFc]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
async function analyze(){if(!file)return;setLoading(true);setError("");try{let f=new FormData();f.append("file",file);let r=await fetch(API+"/predict/pattern",{method:"POST",body:f});let data=await r.json();if(!r.ok)throw new Error(data.detail||"Analysis failed");setPattern(data)}catch(e){setError(e.message)}finally{setLoading(false)}}
async function forecastDemo(){setError("");try{let r=await fetch(API+"/predict/forecast",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({cyclone_id:"DEMO-2026",observations:[{lat:14.2,lon:72.1,wind_kts:45,pressure_hpa:995},{lat:14.7,lon:72.8,wind_kts:52,pressure_hpa:989},{lat:15.1,lon:73.5,wind_kts:58,pressure_hpa:984}]})});let data=await r.json();if(!r.ok)throw new Error(data.detail||"Forecast failed");setFc(data)}catch(e){setError(e.message)}}
return <main><nav><div className="brand">◉ CycloneSense <span>AI</span></div><div className="links"><a href="#analysis">Analysis</a><a href="#forecast">Forecast</a><a href="#platform">Platform</a></div></nav>
<section className="hero"><div><small>◉ MULTI-SOURCE EARTH OBSERVATION</small><h1>See the storm.<br/><em>Before it moves.</em></h1><p>AI-powered tropical cyclone identification, structural classification and short-term forecasting from satellite observations.</p><a className="cta" href="#analysis">Analyze a satellite image →</a></div><div className="storm"><i></i><i></i><i></i><b></b></div></section>
<section className="metrics"><div><Satellite/><b>3+</b><span>Satellite families</span></div><div><CloudLightning/><b>7</b><span>Pattern classes</span></div><div><Activity/><b>24/7</b><span>Inference ready</span></div><div><Wind/><b>AI</b><span>Track + intensity</span></div></section>
<section id="analysis" className="panel"><header><div><small>01 / VISION ANALYSIS</small><h2>Identify cyclone structure</h2></div><span>Upload • Analyze • Explain</span></header><div className="grid"><label className="drop"><Upload size={28}/><strong>{file?file.name:"Drop satellite image here"}</strong><span>PNG / JPG • up to 10 MB</span><input type="file" accept="image/*" onChange={e=>{setFile(e.target.files[0]);setError("")}}/></label><div className="card"><small>IMAGE CLASSIFICATION</small>{pattern?<><h3>{pattern.pattern_predicted.replaceAll("_"," ")}</h3><div className="bar"><i style={{width:(pattern.confidence*100)+"%"}}/></div><p>{Math.round(pattern.confidence*100)}% confidence</p><p className="muted">{pattern.explanation}</p></>:<p className="muted">Upload an image and run analysis.</p>}<button onClick={analyze} disabled={!file||loading}>{loading?"Analyzing…":"Run image analysis"}</button></div></div></section>
<section id="forecast" className="panel dark"><header><div><small>02 / MOTION FORECAST</small><h2>Predict the next move</h2></div><span>Track + intensity</span></header><div className="grid"><div className="map"><div className="line"/><div className="dot d1"/><div className="dot d2"/><div className="dot d3"/></div><div className="card"><small>NEXT POSITION · +12 HOURS</small>{fc?<><h3>{fc.prognostic_trajectory[0].pred_lat.toFixed(2)}°N<br/>{fc.prognostic_trajectory[0].pred_lon.toFixed(2)}°E</h3><p>Wind: <b>{fc.prognostic_trajectory[0].pred_wind_kts.toFixed(0)} kt</b></p><p>Intensity: <b>{fc.intensity_class}</b></p><p>Confidence: <b>{Math.round(fc.confidence_index*100)}%</b></p></>:<p className="muted">Run the demo forecast to verify the API end-to-end.</p>}<button onClick={forecastDemo}>Run forecast demo</button></div></div></section>
{error&&<div className="error">{error}</div>}<footer id="platform"><div className="brand">◉ CycloneSense <span>AI</span></div><p>SIH research prototype · AI × Remote Sensing × Disaster Management</p><small>Not an official meteorological warning system.</small></footer></main>}
createRoot(document.getElementById("root")).render(<App/>);